Гибридный кеш
egrishina/DevSchoolCache pull request #1
Opened 2024-06-27 17:01 UTC by ramilyayus

2024-07-01 18:12 UTC, aryabush requested changes

2024-07-01 18:12 UTC, aryabush commented on DevSchoolCache/HybridCacheService.cs
> +    public async Task<TEntity?> GetOrAddAsync(long id)
Тут происходит завязка на то что в кеше храним только по id, стоит сюда передавать либо cacheKey как стрингу, либо объектом CacheKey

2024-07-01 18:12 UTC, aryabush commented on DevSchoolCache/HybridCacheService.cs
> +        if (entity is not null)
Если прошлый запрос в другом инстансе сервиса в repository.TryGetById(id) вернул null, то entry в редисе будет null и вместо того чтобы вернуть null и не ходить в бд этот код пойдет, что не верно

2024-07-01 18:12 UTC, aryabush commented on DevSchoolCache/Infrastructure/Cache/RedisAdapter.cs
> +        return redisValue.IsNullOrEmpty ? default : JsonConvert.DeserializeObject<TValue>(redisValue!);
Что будет если мы отрефакторим код и поменяем кешируемую модель?

2024-07-01 18:12 UTC, aryabush commented on DevSchoolCacheTests/HybridCacheServiceTests.cs
> +            _redisMock.Verify(x => x.TryGetValueAsync<TestEntity?>(key), Times.Never);
кажется тут несколько тестов в одном получилось. точно все это нужно проверять?

2024-07-01 18:12 UTC, aryabush commented on DevSchoolCacheTests/HybridCacheServiceTests.cs
> +            _memoryCacheMock.Setup(x => x.TryGetValue(key, out It.Ref<TestEntity?>.IsAny)).Returns(false);
кажется стоит еще проверить сценарий, что будет если в _memoryCacheMock значения просто нет, а в redis есть равный null

2024-07-01 18:12 UTC, aryabush commented on DevSchoolCache/HybridCacheService.cs
> +        entity = repository.TryGetById(id);
получается только по Id можно значения получать? Кеши должны поддерживать возможность кешировать данные любого метода и не завязываться на репозитории, а не только по id. посмотрите в сторону  Func<T> valueFactory

2024-07-01 18:12 UTC, aryabush commented on WebApplication/SchoolController.cs
> +    IHybridCacheService<School> schoolService,
Вызывать нужно не кеш, а репозиторий, который бы под капотом вызывал бы кеш

2024-07-01 19:25 UTC, egrishina commented on DevSchoolCache/HybridCacheService.cs
> +        if (entity is not null)
Мы сначала хотели через out параметр entity возвращать, но они в асинхронных методах не поддерживаются

Подскажи, как в таком случае лучше сделать?

2024-07-02 08:28 UTC, aryabush commented on DevSchoolCache/HybridCacheService.cs
> +        if (entity is not null)
а какие еще есть варианты кроме out параметров, если нужно похранить null, но отличить null от отсутствия?

2024-07-02 08:41 UTC, egrishina commented on DevSchoolCache/HybridCacheService.cs
> +        if (entity is not null)
Null object? Типа [такого](https://www.tutorialspoint.com/design_pattern/null_object_pattern.htm)?

2024-07-02 12:04 UTC, aryabush commented on DevSchoolCache/HybridCacheService.cs
> +        if (entity is not null)
А если без наследования?

2024-07-08 10:29 UTC, ramilyayus commented on DevSchoolCache/HybridCacheService.cs
> +        if (entity is not null)
Можно всегда кешровать какой-то объект-обертку над TEntity, получая такой объект из кеша мы будем точно знать что ранее он был закеширован, даже если там Null.
Альтернативно можно было бы сканить все ключи редиса, чтобы отличать закешированный null от отсутствия ключа, но это слишком непроизводительно.

2024-07-08 12:19 UTC, ramilyayus commented on DevSchoolCache/HybridCacheService.cs
> +    public async Task<TEntity?> GetOrAddAsync(long id)
Передаем теперь ключ стрингой

2024-07-08 12:20 UTC, ramilyayus commented on DevSchoolCache/HybridCacheService.cs
> +        if (entity is not null)
Добавили в редис адаптер логику для нулов

2024-07-08 12:21 UTC, ramilyayus commented on DevSchoolCache/Infrastructure/Cache/RedisAdapter.cs
> +        return redisValue.IsNullOrEmpty ? default : JsonConvert.DeserializeObject<TValue>(redisValue!);
Обернули в try-catch чтобы отлавливать изменение контракта (кейс когда не можем распарсить значение из редиса)

2024-07-08 12:22 UTC, ramilyayus commented on DevSchoolCacheTests/HybridCacheServiceTests.cs
> +            _redisMock.Verify(x => x.TryGetValueAsync<TestEntity?>(key), Times.Never);
мы решили что лишним не будет, сейчас вынесли моки репозитория и стало полегче

2024-07-08 12:22 UTC, ramilyayus commented on DevSchoolCacheTests/HybridCacheServiceTests.cs
> +            _memoryCacheMock.Setup(x => x.TryGetValue(key, out It.Ref<TestEntity?>.IsAny)).Returns(false);
добавили такой тест

2024-07-08 12:23 UTC, ramilyayus commented on DevSchoolCache/HybridCacheService.cs
> +        entity = repository.TryGetById(id);
сделали так

2024-07-08 12:23 UTC, ramilyayus commented on WebApplication/SchoolController.cs
> +    IHybridCacheService<School> schoolService,
сделали так

2024-07-08 12:23 UTC, ramilyayus commented
@aryabush поправили коменты, посмотри снова пожалуйста

2024-07-15 16:33 UTC, aryabush commented on DevSchoolCache/School/SchoolRepository.cs
> +        return await _cacheService.GetOrAddAsync(key, () => Set.SingleOrDefault(s => s.Id == id));
тут await не нужен. достаточно убрать async. иначе это оверхед на async без причин

2024-07-15 16:35 UTC, aryabush approved these changes
Один коммент с async. В остальном ок. По этому считаю принятым

2024-08-16 14:31 UTC, closed without merging